In [74]:
import numpy as np

grid = np.array([[0,0,0,1,1],[1,1,0,0,0],[1,1,0,0,0],[0,0,0,1,1],[0,0,0,1,0]])
print(grid)


[[0 0 0 1 1]
 [1 1 0 0 0]
 [1 1 0 0 0]
 [0 0 0 1 1]
 [0 0 0 1 0]]


In [86]:
def get_Adjacents(x,y,grid):
    
    x1 = x-1
    x2 = x+1
    y1 = y-1
    y2 = y+1
    
    L = []
    
    p = list(range(0,grid.shape[0]))
    q = list(range(0,grid.shape[1]))
    
    if x1 in p:
        if grid[x1][y] == 1:
            L.append((x1,y))
    
    if x2 in p:
        if grid[x2][y] == 1:
            L.append((x2,y))
        
    if y1 in q:
        if grid[x][y1] == 1:
            L.append((x,y1))
        
    if y2 in q:
        if grid[x][y2] == 1:
            L.append((x,y2))
        
    return L

In [91]:
def no_of_Islands(grid):
    
    total_islands = 0
    n,m = grid.shape
    
    seen = set()
    Islands = []
    
    for i in range(n):
        for j in range(m):
            
            if (i,j) not in seen:
                seen.add((i,j))
                
                if grid[i][j] == 1:
                    
                    print("Node",[i,j]," = 1")
                    island = [(i,j)]
                    island_c = island.copy()
                    
                    while(len(island) != 0):
                        p,q = island.pop()
                        
                        adjacents = get_Adjacents(p,q,grid)
                    
                        for a in adjacents:
                            if a not in island_c:
                                island.insert(0,a)
                                island_c.append(a)
                                seen.add(a)
                                
                    Islands.append(island_c)
                    total_islands += 1
                    
                else:
                    continue
                    
    print("Total no.of Islands",total_islands)
    return total_islands     
                

In [92]:
no_of_Islands(grid)

Node [0, 3]  = 1
Node [1, 0]  = 1
Node [3, 3]  = 1
Total no.of Islands 3


3

In [96]:
13//5

2

In [126]:
s = '123456'

if len(s)%2 == 0:
    o = ''
    index = len(s)//2 - 1
    print("index",index)
    for i in range(len(s)//2):
        o = s[index + 1 + i] + o + s[index - i]
        print("o",o)
else:
    index = len(s)//2 
    
    o = s[index]
    for i in range(len(s)//2):
        o = s[index + 1 + i] + o + s[index-(1 + i)]
        print("o",o)

    

index 2
o 43
o 5432
o 654321


In [290]:
class User:
    
    def __init__(self, userid):
        self.user = userid
        self.username_list = []
        self.username = ''
        self.connections = {}
        self.deleted_connections = set()
        
    def addUser(self,username):
        if str(username) not in self.username_list:
            self.username_list.append(str(username))
            self.username = username
            return self.username
        else:
            pritn("User ID already exists")
        
    def getUsername(self,userid):
        return userid.username
    
    def addConnection(self, userid1, userid2):
        if userid1.username != '' and userid2.username != '':
            if userid2.username not in userid1.connections:
                userid1.connections[userid2] = userid2.username 
            if userid1.username not in userid2.connections:
                userid2.connections[userid1] = userid1.username 
        else:
            print("One of the user's does not exist")
    
    def areConnected(self,userid1,userid2):
        if userid1 in userid2.connections:
            return True
        else:
            return False
    
    def deleteUser(userid):
        if userid.username != '':
            self.username_list.remove(userid.username)
            userid.username = ''
            userid.connections = []
        else:
            pritn("User does not exist")
            
    def deleteConnection(self,userid1, userid2):
        if userid1.username != '' and userid2.username != '':
            if userid1 in userid2.connections:
                userid2.connections.pop(userid1)
                userid2.deleted_connections.add(userid1)
            if userid2 in userid1.connections:
                userid1.connections.pop(userid2)
                userid1.deleted_connections.add(userid2)
        else:
            print("One of the user's does not exist")
            
    def getRecommendedConnections(self,userid):
        recommendations = set()
        for i in userid.connections:
            for j in i.connections:
                if j.user != userid.user:
                    recommendations.add(j.user)
                    
                recommendations.union(j.deleted_connections)

        return recommendations

In [291]:
user1 = User("user1")
user1.addUser("username1")
user1.getUsername(user1)
user2 = User("username2")
user2.addUser("username2")

user3 = User("username3")
user3.addUser("username3")

user4 = User("username4")
user4.addUser("username4")

user1.addConnection(user1,user2)
user2.addConnection(user2,user3)

user1.areConnected(user1,user2)

user2.connections[user1]

user1.getRecommendedConnections(user1)

{'username3'}